!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 15, y: 1, z: 15}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 0, z: 26}
      - !Vector3 {x: 20, y: 0, z: 14}
      - !Vector3 {x: 26, y: 0, z: 20}
      - !Vector3 {x: 14, y: 0, z: 20}
      rotations: [0, 0, 0, 0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 13, y: 2, z: 1}
      - !Vector3 {x: 13, y: 2, z: 1}
      - !Vector3 {x: 1, y: 2, z: 11}
      - !Vector3 {x: 1, y: 2, z: 11}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 23.5, y: 0, z: 16.5}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 4, y: 0.5, z: 4}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 23.5, y: 0, z: 23.5}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 4, y: 0.5, z: 4}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 23.5, y: 1, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 1, y: 2, z: 5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 17, y: 1, z: 21}
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5}
