!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 100
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 5, y: 1, z: 5}
      rotations: [0]
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 6, y: 1, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 3, y: 0.5, z: 40}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 34, y: 1, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 2, y: 0.5, z: 9}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 20, y: 1, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 4, y: 0.5, z: 4}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 34, y: 1, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 1, y: 2, z: 5}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 6, y: 1, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 1, y: 2, z: 5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 35, y: 1, z: 15}
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5}
